import yfinance as yf
import pandas as pd
import numpy as np

# Target: Commercial International Bank (Egypt) and the VanEck Egypt Index ETF
tickers = ["COMI.CA", "EGPT"]

def build_mena_pipeline(tickers):
    print("Initiating MENA Equity Data Scraper...\n")
    
    for ticker in tickers:
        print(f"Scraping 2 years of daily data for {ticker}...")
        
        # Download the data from the API
        data = yf.download(ticker, period="2y", interval="1d")
        
        if data.empty:
            print(f"Failed to pull data for {ticker}. Check API connection.\n")
            continue

        # Clean missing values (The "Data Plumbing")
        data.dropna(inplace=True)

        # Calculate Daily Returns
        data['Daily_Return'] = data['Close'].pct_change()

        # Calculate 20-Day Moving Average
        data['20_Day_MA'] = data['Close'].rolling(window=20).mean()

        # Calculate 20-Day Rolling Volatility (Annualized)
        data['20_Day_Volatility'] = data['Daily_Return'].rolling(window=20).std() * np.sqrt(252)

        # Drop the new NaNs generated by the rolling windows
        data.dropna(inplace=True)

        # Export to a clean CSV for econometric analysis
        filename = f"{ticker}_cleaned_dataset.csv"
        data.to_csv(filename)
        
        print(f"Pipeline complete. Saved localized dataset: {filename}\n")

if __name__ == "__main__":
    build_mena_pipeline(tickers)
    print("All MENA data structured and ready for econometric analysis.")
